services:
  crypto-arbitrage-scheduler:
    build: .
    container_name: crypto-arbitrage-scheduler
    restart: unless-stopped
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - KUCOIN_API_KEY=${KUCOIN_API_KEY}
      - KUCOIN_API_SECRET=${KUCOIN_API_SECRET}
      - KUCOIN_API_PASSPHRASE=${KUCOIN_API_PASSPHRASE}
      - DASHBOARD_SECRET_KEY=${DASHBOARD_SECRET_KEY}
      - FLASK_ENV=production
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=${LOG_FILE:-/app/logs/crypto_arbitrage_bot.log}
      - TRADING_INTERVAL=${TRADING_INTERVAL:-300}
    volumes:
      - /var/www/crypto_arbitrage_bot/db:/app/db
      - /var/www/crypto_arbitrage_bot/logs:/app/logs
    command: ["python", "src/main.py", "--skip-network-check", "--dry-run"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  crypto-arbitrage-web:
    build: .
    container_name: crypto-arbitrage-web
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - KUCOIN_API_KEY=${KUCOIN_API_KEY}
      - KUCOIN_API_SECRET=${KUCOIN_API_SECRET}
      - KUCOIN_API_PASSPHRASE=${KUCOIN_API_PASSPHRASE}
      - DASHBOARD_SECRET_KEY=${DASHBOARD_SECRET_KEY}
      - FLASK_ENV=production
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=${LOG_FILE:-/app/logs/crypto_arbitrage_bot.log}
      - TRADING_INTERVAL=${TRADING_INTERVAL:-300}
    volumes:
      - /var/www/crypto_arbitrage_bot/db:/app/db
      - /var/www/crypto_arbitrage_bot/logs:/app/logs
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "2", "--timeout", "120", "--access-logfile", "-", "--error-logfile", "-", "wsgi:application"]
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/login', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 